name: docker-swarm-deployer
author: Simba
description: A GitHub Action that enables you to publish your app as a Docker stack to a remote Docker swarm.
inputs:
  remote_host:
    description: Docker host to connect to
    required: true
  ssh_private_key:
    description: SSH private key to use to connect
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
